### ISSUE TITLE
sample code error for Chapter 4

### ISSUE THREAD

**Issue by ricksu** [thoughtfulml/examples-in-python#18]
I tried to run the example of Chapter 4 -- naive_bayes, but got error.
I use Python 2.7.

Command:
python crossvalidate.py 

Error I got:
```
Traceback (most recent call last):
  File "crossvalidate.py", line 75, in <module>
    validate(trainer, emails)
  File "crossvalidate.py", line 50, in validate
    classification = trainer.classify(email)
  File "/home/rick/source/MachineLearning/python/examples-in-python/naive_bayes/spam_trainer.py", line 107, in classify
    score = self.score(email)
  File "/home/rick/source/MachineLearning/python/examples-in-python/naive_bayes/spam_trainer.py", line 86, in score
    self.train()
  File "/home/rick/source/MachineLearning/python/examples-in-python/naive_bayes/spam_trainer.py", line 70, in train
    for token in Tokenizer.unique_tokenizer(email.body()):
  File "/home/rick/source/MachineLearning/python/examples-in-python/naive_bayes/email_object.py", line 49, in body
    decoded_parts.append(part.decode('utf-8'))
  File "/home/rick/.virtualenvs/machine-learning/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa4 in position 286: invalid start byte
```

Could you tell me why I got this error? And how to fix it?

thanks a lot.

**Comment by hexgnu** [comment]
Hey there, have you tried running this on Python 3? We went through and updated quite a few of the files to work on Python 3.

**Comment by hexgnu** [comment]
Also what OS are you using?

**Comment by ricksu** [comment]
Hi Hexgnu,

thanks for reply.
I tried with Ubuntu 16.04 in virtualbox VM, also I tried both with Python27 and Python3, but got same error 
_UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 286: invalid start byte ._

I still don't know why I got this error...

**Comment by hexgnu** [comment]
https://github.com/thoughtfulml/examples-in-python/commit/9258bc537dae11f5d8ea372f18cf49cc92036390
